[config]
schemaVersion = "0.0.1"

[package]
namespace = "MicheliniDev"
name = "HPNumbers"
versionNumber = "1.0.3"
description = "Shows Yi's and Boss' HP Numbers"
websiteUrl = "https://github.com/MicheliniDev/NineSols-HPNumbersMod"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.0.2"
"ninesolsmodding-BepinExConfigurationManager" = "18.3.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
